name: vibe
description: A beautiful music streaming app built with Flutter and Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.0
  firebase_analytics: ^12.0.0

  # Audio
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  just_audio_background: ^0.0.1-beta.17

  # State Management
  provider: ^6.1.5

  # UI & Animations
  cached_network_image: ^3.4.1
  flutter_slidable: ^4.0.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  animated_bottom_navigation_bar: ^1.4.0

  # Utilities
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  # Icons & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700